### ISSUE TITLE
How to toggle the menu? (VoxeLibre)

### ISSUE THREAD

**Issue by 320kg** [JustinLaw64/craft_lookup#1] opened 2024-07-30 08:45 UTC
The title is pretty self explanatory. When I open an inventory or a crafting table I don't see this mod anywhere. Perhaps I am stupid?

**Comment by JustinLaw64** [comment] 2024-08-09 03:26
The mod was only designed for Minetest Game about 5 years ago, which at the time, had no crafting tables at all. The mod is supposed to add a new tab to the inventory screen to allow lookups of crafting recipes. However, it is possible that the game was changed afterwards in a way that broke my mod.

I don't have Minetest installed right now, but I'll let you know once I look into it.

**Comment by JustinLaw64** [comment] 2024-08-09 04:06
Okay, I know what's going on. I installed Minetest real quick and tried out VoxelLibre (I missed the tag in your title).

At the time this mod was made, that game was called "MineClone." This mod does not work at all there because it does not have an inventory screen mod called "sfinv." However, VoxelLibre already has its own recipe book which you can get to from its inventory screen.

I'll go ahead and close this issue because this is not a bug. VoxelLibre is simply not supported by my mod. However, if you'd like to see support added, then feel free to open a new issue telling me why my mod would improve VoxelLibre over its built-in recipe book.

**Closed as completed by JustinLaw64** 2024-08-09 04:06 UTC
